### ISSUE TITLE
threat

### ISSUE THREAD

**Issue by KeithKimani** [learn-co-curriculum/dsc-welcome-intro#3] opened 2024-09-16 06:22 UTC
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment] 2024-09-16 14:16
Thanks for reaching out, but it is unclear what the issue is. So we'll close the issue; however, please reopen with more details if there is still an issue. Thank you.

**Closed as completed by bpurdy-ds** 2024-09-16 14:16 UTC
